- name: Deploy Docker Container
  hosts: servers
  become: true

  tasks:
    - name: Pull image from Docker Hub
      docker_container:
        name: webapp
        image: httpd:latest
        state: started
        ports:
          - "8080:80"
